name: Python CI Pipeline

on:
  push:
    branches:
      - main   # Pipeline trigger saat push ke main

jobs:

  # ============================
  # 1. LINTING (Super-Linter)
  # ============================
  super-lint:
    name: Lint Code Base (Super-Linter)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true   # aktifkan Python Linter (Flake8)
          VALIDATE_ALL_CODEBASE: true

  # ============================
  # 2. UNIT TEST (Pytest)
  # ============================
  run-tests:
    name: Run Unit Tests (pytest)
    runs-on: ubuntu-latest
    needs: super-lint   # hanya test kalau lint sukses
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run unit tests
        run: pytest
